#include "PlatinumA3Editor.h"

#include "Kismet2/KismetEditorUtilities.h"
#include "Logging/StructuredLog.h"
#include "Runtime/FleeSystem/FleeLeaderComponent.h"
#include "Runtime/RallySystem/RallyEmitterComponent.h"
#include "Runtime/RallySystem/RallyReceiverComponent.h"
#include "Runtime/SheepSystem/SheepComponent.h"

DEFINE_LOG_CATEGORY(PlatinumA3Editor)

#define LOCTEXT_NAMESPACE "FPlatinumA3EditorModule"
void FPlatinumA3EditorModule::StartupModule()
{
    UE_LOGFMT(PlatinumA3Editor, Warning, "PlatinumA3Editor: Log Started");

    PrepareAutoGeneratedDefaultEvents();
}

void FPlatinumA3EditorModule::ShutdownModule()
{
    UE_LOGFMT(PlatinumA3Editor, Warning, "PlatinumA3Editor: Log Ended");

    FKismetEditorUtilities::UnregisterAutoBlueprintNodeCreation(this);
}

void FPlatinumA3EditorModule::PrepareAutoGeneratedDefaultEvents()
{
    
    //// RALLY SYSTEM ////
    ///Rally Emitter
    RegisterDefaultEvents(URallyEmitterComponent, JuicyEmitSignal);
    ///Rally Receiver
    RegisterDefaultEvents(URallyReceiverComponent, JuicyNotify);
    RegisterDefaultEvents(URallyReceiverComponent, JuicyUnNotify);

    //// SHEEP SYSTEMS ////
    ///Sheep Component
    RegisterDefaultEvents(USheepComponent, JuicyCapture);
    RegisterDefaultEvents(USheepComponent, JuicyDie);
}

#undef LOCTEXT_NAMESPACE
    
IMPLEMENT_MODULE(FPlatinumA3EditorModule, PlatinumA3Editor)